### ISSUE TITLE
Creacion de modelo relacional

### ISSUE THREAD

**Issue by jdomingu98** [la-true-liga/mercatech-express-api#9]
Generar un entidad/relación o un modelo relacional con la estructura de tablas y relaciones del proyecto.

Para generar dicho esquema se puede usar tanto **Prisma** (ORM) como **MySQL Workbench**

Una vez creado el modelo en uno de los dos lugares (Workbench o Prisma) generar una sincronización y migración de los datos. La migración debe subirse al repositorio.

PD: Antes de crear el modelo, todos los miembros del equipo deben aprobar el esquema (adjuntar foto al historial de la issue)

**Comment by jdomingu98** [comment]
![modelo relacional](https://github.com/la-true-liga/mercatech-express-api/assets/97060625/138e0ca7-cf5c-4d8d-99fe-eae3a00c2e90)

**Comment by ruzafa8** [comment]
Por mi parte lo veo bastante bien.

## Cosas que se me han ocurrido
(Algunas cosas desde el desconocimiento, que no me acuerdo de cómo iban los diagramas estos :$)
- A la tabla `list_item` le faltaría un **num_items** (Hablamos de ponerle varias opciones: kg, unidades, litros, ml...). Pienso que no deberíamos complicarnos, poner nº de items y ya (KISS).

- Entiendo que los 3 _int_ de la tabla `list` (**compra_userId**, **despensa_userId**, **custom_userId**) son las _FK_ de las 3 relaciones y que por cada usuario solo puede haber una lista de compra y una despensa, pero yo lo entiendo por que conozco el contexto, no sé si hay alguna forma de dejar esa eso mejor especificado (algo así como nombrar las relaciones o indicar cuál _FK_ corresponde a cada relación) (Esto es más bien duda :))

- (Esto es también duda, o quizás algo para apuntar en el backlog para mirar a posteriori, o lo mismo ignorarlo si es muy complejo xd) Supongo que para que estas restricciones sean efectivas en BBDD habría que crearlas específicamente, quiero decir: 
1. Una lista sin **compra_userId**, **despensa_userId** o **custom_userId** no tendría sentido (Osea, no pueden ser _null_ los 3)
2. Una lista con más de uno de estos campos rellenos: **compra_userId**, **despensa_userId** o **custom_userId** (osea, 2 tienen que ser _null_ sí o sí y el otro tiene que tener un valor)
3. **compra_userId** y **despensa_userId** deben de ser uniques (no sé si se podría dejar indicado de alguna forma en el diagrama, o lo mismo al haber indicado la relación ya ocurre).

- También renta unificar idioma (_everything_ en inglés, o to en español)

**Comment by ruzafa8** [comment]
Genial, más que nada era cosas por tener en cuenta... Y no me enteré que había PR hasta después de enviar esto JAJAJJA

**Comment by jdomingu98** [comment]
Vava no pasa nada. Estaría bien configurar si es posible que estos comentarios lleguen al correo o algo así porque si no me veo más de un despiste como este jajajaaj
